version: '3'

services:
  django-app:
    restart: always
    build: ./django-app
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - django-app:/usr/src/app
      - django-app-static:/usr/src/app/static
    env_file: .env
    environment:
      DEBUG: 'true'
    command: /usr/local/bin/gunicorn docker_django.wsgi:application -w 2 -b :8000

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - django-app-static:/www/static
    links:
      - django-app:django-app

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  django-app:
  django-app-static:
  pgdata:
  redisdata:
